spring:
  application:
    name: payment-consumer

  datasource:
    url: jdbc:postgresql://localhost:5432/nano_banking_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          format_sql: true
          dialect: org.hibernate.dialect.PostgreSQLDialect

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: payment-callback-group
      auto-offset-reset: latest
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

kafka:
  topics:
    payment-callbacks: payment-callbacks

server:
  port: 8084

