server:
  port: 8082

spring:
  application:
    name: payment-api

  datasource:
    url: jdbc:postgresql://localhost:5432/nano_banking_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

services:
  paymentCallback:
    url: http://localhost:8083/api/v1/payments/callback